# Generated by Django 5.1.5 on 2025-01-29 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_catastral', models.CharField(max_length=27, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('valor_catastral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_ext', models.CharField(max_length=5)),
                ('num_int', models.CharField(blank=True, default='N/A', max_length=5)),
                ('col_fracc', models.CharField(max_length=50)),
                ('localidad', models.CharField(default='MINATITLAN', max_length=25)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contribuyente')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('estado_fisico', models.CharField(max_length=25)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uso', models.CharField(max_length=25)),
                ('antiguedad', models.PositiveSmallIntegerField()),
                ('tenencia', models.CharField(default='N/A', max_length=25)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.predio')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(verbose_name=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefonico', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=15)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contribuyente')),
            ],
            options={
                'unique_together': {('numero_telefonico', 'contribuyente', 'tipo')},
            },
        ),
    ]
