# Generated by Django 5.1.5 on 2025-01-29 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=4)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estatus_pago', models.CharField(max_length=30)),
                ('estatus_descuento', models.CharField(default='NO SOLICITADO', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.predio')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoAdeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_recargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_adeudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago_predial.adeudo')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPago',
            fields=[
                ('folio', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contribuyente')),
                ('id_adeudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago_predial.adeudo')),
            ],
        ),
    ]
